# Readme format of package.
# Available values:
#  package: Package object.
#  dependenciesFormatted: Formatted dependencies as text.
body: |
   # {package.name}

   {package.displayName}

   ## Info
   - **Version**: `{package.version}`
   - **Unity**: `{package.unity}`

   ### Dependencies

   {dependenciesFormatted}

   ### Description

   {package.description}

   ## How to Install

   Read about how to install any packages from the `Unity Game Framework` registry: [Install Package](https://github.com/unity-game-framework/ugf-documentation/wiki/Install-Package).

# Dependency format of package dependencies.
# Available values:
#   package: Package object.
#   dependency: Dependency object.
#     name: Name of dependency.
#     version: Version of dependency.
dependency: |
   - `{dependency.name}`: `{dependency.version}`

# Used instead of 'dependency' format when no any dependencies found.
dependenciesEmpty: |
   - N/A
