name: 'Package Readme'
description: 'Creates package readme.'
inputs:
  package:
    description: 'Path to package.json file.'
    required: true
  template:
    description: 'Path to readme template file.'
    default: .github/package-readme.md
    required: true
  token:
    description: 'GitHub token used by action.'
    default: ${{ github.token }}
    required: true
  config:
    description: 'Path to config with generate settings.'
    default: .github/package-readme.yml
    required: true
  configType:
    description: 'Type of config representation, possible values "yaml" or "json".'
    default: yaml
    required: true
  outputType:
    description: 'Type of result output, possible values "action", "file" or "all".'
    default: action
    required: true
  outputPath:
    description: 'Path of output file.'
    default: ${{ github.action }}
    required: true
outputs:
  result:
    description: 'Readme generation result.'
runs:
  using: 'node12'
  main: 'dist/index.js'
