name: 'Package Readme'
description: 'Creates package readme.'
inputs:
  token:
    description: 'GitHub token used by action.'
    default: ${{ github.token }}
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
